title: Qirui Wang's Homepage
page-top-title: Qirui Wang
top-section-bg-text: 
home-subtitle: Qirui Wang
copyright-text: '&copy; Yourname 2023-2025. All Rights Reserved.'
site_name: Qirui Wang
site_description: Undergraduate in software engineering, Wuhan University
email: qiruiwang@whu.edu.cn
